# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5216ed0256efdd6080c8cfa6b01a2279c83ecb98a6ea87a8a95c2454290e6da01b08f87a1029c43251b0376a9d1a5fe0fcc5e02075ef426df48b39290800be26

test:
  secret_key_base: 484abbb02b1b6b181fd2f0c3f05ed9a86d4e12efb13deb234c58165d6173d89853133ef8695e3f19f7dd1ab64132cf99e25cf8f9cd9e55c02dd962d29980725b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
